//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valil.Chess.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valil.Chess.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black pawns must not have rank 8..
        /// </summary>
        internal static string BlackPawnRank8Msg {
            get {
                return ResourceManager.GetString("BlackPawnRank8Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black to move.
        /// </summary>
        internal static string BlackToMoveText {
            get {
                return ResourceManager.GetString("BlackToMoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmate.
        /// </summary>
        internal static string CheckmateText {
            get {
                return ResourceManager.GetString("CheckmateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string CheckText {
            get {
                return ResourceManager.GetString("CheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw: 50-move rule.
        /// </summary>
        internal static string Draw50MoveRuleText {
            get {
                return ResourceManager.GetString("Draw50MoveRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw: Insufficient material.
        /// </summary>
        internal static string DrawInsufficientMaterialText {
            get {
                return ResourceManager.GetString("DrawInsufficientMaterialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw: Repetition.
        /// </summary>
        internal static string DrawRepetitionText {
            get {
                return ResourceManager.GetString("DrawRepetitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal long castling availability for white king..
        /// </summary>
        internal static string IllegalBlackKingLongCastlingMsg {
            get {
                return ResourceManager.GetString("IllegalBlackKingLongCastlingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal short castling availability for black king..
        /// </summary>
        internal static string IllegalBlackKingShortCastlingMsg {
            get {
                return ResourceManager.GetString("IllegalBlackKingShortCastlingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal board status..
        /// </summary>
        internal static string IllegalBoardStatusMsg {
            get {
                return ResourceManager.GetString("IllegalBoardStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal CAN move format..
        /// </summary>
        internal static string IllegalCANFormatMsg {
            get {
                return ResourceManager.GetString("IllegalCANFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal CAN move..
        /// </summary>
        internal static string IllegalCANMoveMsg {
            get {
                return ResourceManager.GetString("IllegalCANMoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal en passant target..
        /// </summary>
        internal static string IllegalEPTargetMsg {
            get {
                return ResourceManager.GetString("IllegalEPTargetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal FEN board format..
        /// </summary>
        internal static string IllegalFENFormatMsg {
            get {
                return ResourceManager.GetString("IllegalFENFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal initial game state..
        /// </summary>
        internal static string IllegalGameStateMsg {
            get {
                return ResourceManager.GetString("IllegalGameStateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IllegalMoveMsg.
        /// </summary>
        internal static string IllegalMoveMsg {
            get {
                return ResourceManager.GetString("IllegalMoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal SAN move format..
        /// </summary>
        internal static string IllegalSANFormatMsg {
            get {
                return ResourceManager.GetString("IllegalSANFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal SAN move..
        /// </summary>
        internal static string IllegalSANMoveMsg {
            get {
                return ResourceManager.GetString("IllegalSANMoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal long castling availability for white king..
        /// </summary>
        internal static string IllegalWhiteKingLongCastlingMsg {
            get {
                return ResourceManager.GetString("IllegalWhiteKingLongCastlingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal short castling availability for white king..
        /// </summary>
        internal static string IllegalWhiteKingShortCastlingMsg {
            get {
                return ResourceManager.GetString("IllegalWhiteKingShortCastlingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one black king..
        /// </summary>
        internal static string MoreThanOneBlackKingMsg {
            get {
                return ResourceManager.GetString("MoreThanOneBlackKingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one white king..
        /// </summary>
        internal static string MoreThanOneWhiteKingMsg {
            get {
                return ResourceManager.GetString("MoreThanOneWhiteKingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No black king..
        /// </summary>
        internal static string NoBlackKingMsg {
            get {
                return ResourceManager.GetString("NoBlackKingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ply must be greater or equal to 0..
        /// </summary>
        internal static string NonNegativePlyMsg {
            get {
                return ResourceManager.GetString("NonNegativePlyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The promotion type is not set..
        /// </summary>
        internal static string NoPromotionMsg {
            get {
                return ResourceManager.GetString("NoPromotionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The side which is not to move cannot be in check..
        /// </summary>
        internal static string NoSideNotToMoveCheckMsg {
            get {
                return ResourceManager.GetString("NoSideNotToMoveCheckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No white king..
        /// </summary>
        internal static string NoWhiteKingMsg {
            get {
                return ResourceManager.GetString("NoWhiteKingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null board..
        /// </summary>
        internal static string NullBoardMsg {
            get {
                return ResourceManager.GetString("NullBoardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null CAN..
        /// </summary>
        internal static string NullCANMsg {
            get {
                return ResourceManager.GetString("NullCANMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null FEN..
        /// </summary>
        internal static string NullFENMsg {
            get {
                return ResourceManager.GetString("NullFENMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null game..
        /// </summary>
        internal static string NullGameMsg {
            get {
                return ResourceManager.GetString("NullGameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null move..
        /// </summary>
        internal static string NullMoveMsg {
            get {
                return ResourceManager.GetString("NullMoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null SAN..
        /// </summary>
        internal static string NullSANMsg {
            get {
                return ResourceManager.GetString("NullSANMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of moves must be greater or equal to 1..
        /// </summary>
        internal static string PositiveMoveNoMsg {
            get {
                return ResourceManager.GetString("PositiveMoveNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stalemate.
        /// </summary>
        internal static string StalemateText {
            get {
                return ResourceManager.GetString("StalemateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many black pieces..
        /// </summary>
        internal static string TooManyBlackPiecesMsg {
            get {
                return ResourceManager.GetString("TooManyBlackPiecesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many white pieces..
        /// </summary>
        internal static string TooManyWhitePiecesMsg {
            get {
                return ResourceManager.GetString("TooManyWhitePiecesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White pawns must not have rank 1..
        /// </summary>
        internal static string WhitePawnRank1Msg {
            get {
                return ResourceManager.GetString("WhitePawnRank1Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White to move.
        /// </summary>
        internal static string WhiteToMoveText {
            get {
                return ResourceManager.GetString("WhiteToMoveText", resourceCulture);
            }
        }
    }
}
